from django.db import models


# Create your models here.
class Node_info(models.Model):
    BaseInfo = models.CharField(max_length=2000, blank=True)
    NodeName = models.CharField(max_length=2000, blank=True)
    Time = models.DateTimeField()
    RunTime = models.CharField(max_length=2000, blank=True)
    LoadInfo = models.CharField(max_length=2000, blank=True)
    Load1 = models.FloatField(max_digits=10, decimal_places=2)
    Load5 = models.FloatField(max_digits=10, decimal_places=2)
    Load15 = models.FloatField(max_digits=10, decimal_places=2)
    TaskInfo = models.CharField(max_length=2000, blank=True)
    Taskstotal = models.IntegerField()
    TaskRunning = models.IntegerField()
    TaskSleeping = models.IntegerField()
    TaskStopped = models.IntegerField()
    Taskzombie = models.IntegerField()
    CpuInfo = models.CharField(max_length=2000, blank=True)
    Us = models.FloatField(max_digits=10, decimal_places=2)
    Sy = models.FloatField(max_digits=10, decimal_places=2)
    Ni = models.FloatField(max_digits=10, decimal_places=2)
    Id = models.FloatField(max_digits=10, decimal_places=2)
    Wa = models.FloatField(max_digits=10, decimal_places=2)
    Hi = models.FloatField(max_digits=10, decimal_places=2)
    Si = models.FloatField(max_digits=10, decimal_places=2)
    MemInfo = models.CharField(max_length=2000, blank=True)
    Memtotal = models.IntegerField()
    Memused = models.IntegerField()
    Memfree = models.IntegerField()
    Membuffer = models.IntegerField()
    DiskInfo = models.CharField(max_length=2000, blank=True)
    FileSysName = models.CharField(max_length=2000, blank=True)
    FileSysTotal = models.IntegerField()
    FileSysFree = models.IntegerField()
    MountPoint = models.CharField(max_length=2000, blank=True)
    IOinfo = models.CharField(max_length=2000, blank=True)
    DeviceName = models.CharField(max_length=2000, blank=True)
    Tps = models.FloatField(max_digits=10, decimal_places=2)
    ReadSpeed = models.FloatField(max_digits=10, decimal_places=2)
    ReadToral = models.IntegerField()
    WriteSpeed = models.FloatField(max_digits=10, decimal_places=2)
    WriteTotal = models.IntegerField()
