#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 16-12-22 下午8:44
# @Author  : mengyuGuo
# @Site    : 
# @File    : vnfd_example.py
# @Software: PyCharm

      {
         "name":"bind9",
         "vendor":"fokus",
         "version":"0.1",
         "lifecycle_event":[
            {
               "event":"CONFIGURE",
               "lifecycle_events":[
			"fhoss_relation_joined.sh",
			"icscf_relation_joined.sh",
			"scscf_relation_joined.sh",
			"pcscf_relation_joined.sh",
			"mmechess_relation_joined.sh"
               ]
            },
            {
               "event":"INSTANTIATE",
               "lifecycle_events":[
			"bind9_install.sh"
               ]
            },
            {
               "event":"START",
               "lifecycle_events":[
			"generate_zone_file.sh",
			"bind9_restart.sh"
               ]
            }
         ],
         "configurations":{
            "name":"bind9-configuration",
            "configurationParameters":[
	       {
                  "confKey":"realm",
                  "value":"open-ims.test"
               },
	       {
                  "confKey":"useFloatingIpsForEntries",
                  "value":"true"
               }
            ]
         },
         "vdu":[
            {
               "vm_image":[],
               "scale_in_out":1,
               "vnfc":[
                  {
                     "connection_point":[
                        {
			         "floatingIp":"random",
                           "virtual_link_reference":"mgmt"
                        }
                     ]
                  }
               ]
            }
         ],
         "virtual_link":[
            {
               "name":"mgmt"
            }
         ],
         "deployment_flavour":[
            {
               "flavour_key":"m1.small"
            }
         ],
         "type":"bind9",
         "endpoint":"generic",
         "requires":{
            "fhoss":{
                  "parameters":[ "name", "port", "mgmt", "mgmt_floatingIp" ]
            },"icscf":{
                  "parameters":[ "name", "port", "mgmt", "mgmt_floatingIp" ]
            }, "scscf":{
                  "parameters":[ "name", "port", "mgmt", "mgmt_floatingIp" ]
            }, "pcscf":{
                  "parameters":[ "name", "port", "mgmt", "mgmt_floatingIp" ]
            }
      }
}


vnfd:vnfd-catalog:
    vnfd:
    -   id: cirros_vnfd
        name: cirros_vnfd
        short-name: cirros_vnfd
        description: Generated by OSM pacakage generator
        vendor: OSM
        version: '1.0'

        # Place the logo as png in icons directory and provide the name here
        logo: cirros-64.png

        # Management interface
        mgmt-interface:
            vdu-id: cirros_vnfd-VM

        # Atleast one VDU need to be specified
        vdu:
        -   id: cirros_vnfd-VM
            name: cirros_vnfd-VM
            description: cirros_vnfd-VM
            count: 1

            # Flavour of the VM to be instantiated for the VDU
            vm-flavor:
                vcpu-count: 1
                memory-mb: 512
                storage-gb: 1

            # Image including the full path
            image: '/mnt/powervault/virtualization/osm/CirrOS/cirros-0.3.4-x86_64-disk.img'

            external-interface:
            # Specify the external interfaces
            # There can be multiple interfaces defined
            -   name: eth0
                virtual-interface:
                    type: OM-MGMT
                    bandwidth: '0'
                    vpci: 0000:00:0a.0
                vnfd-connection-point-ref: eth0

        connection-point:
            -   name: eth0
                type: VPORT
