# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rsp',
        ),
    ]
