# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrator', '0002_delete_rsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='rsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rspRequestId', models.BigIntegerField()),
                ('sfNameList', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
