# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_auto_20161209_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsp',
            old_name='rspResponse_json',
            new_name='sfNameList',
        ),
    ]
